Fix/location info for all registers
SoftmedTanzania/opensrp-client-chw-core pull request #85
Opened 2022-06-27 13:24 UTC by dev-billy

2022-06-28 08:32 UTC, cozej4 requested changes, later dismissed

2022-06-28 08:32 UTC, cozej4 commented on gradle.properties
>  VERSION_CODE=6
Please also update this version code

2022-06-28 08:40 UTC, dev-billy commented on gradle.properties
>  VERSION_CODE=6
On it

2022-06-29 13:04 UTC, cozej4 approved these changes

2022-06-29 13:13 UTC, merged